### ISSUE TITLE
Add/Optimize current documents

### ISSUE THREAD

**Issue by Okabe-Rintarou-0** [kmesh-net/kmesh#546]
**Task description**:
Add/Optimize current documents. See reasons in #401 
**Solution**:

TODO-LIST:
+ [x] How to develop and deploy kmesh from scratch(use kind/ use vmware to utilize openEuler 23.03 enhanced kernel)
+ [x] How to check logs(ebpf and user-space), and set/get logger level
+ [x] Build Flags about Enhanced Kernel

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.
